# docker-compose.yaml
services:
  clone-detector:
    image: cljdetector
    command: clear 
    ports:
      - 8080:3000
    volumes:
      - ./Containers/cljdetector:/usr/src/app
      - qc-volume:/QualitasCorpus
    environment:
      DBHOST: dbstorage
      SOURCEDIRtest: "/usr/src/app/test/data"
      SOURCEDIReclipse: "/QualitasCorpus/QualitasCorpus-20130901r/Systems/eclipse_SDK"
      SOURCEDIR: "/QualitasCorpus/QualitasCorpus-20130901r"
      CHUNKSIZE: 20

  monitor:
    image: monitortool
    ports:
      - 8081:8080
    environment:
      DBHOST: dbstorage
      LOG_INTERVAL: 1
    volumes:
      - ./archives:/app/archives  # Mount archives directory
    depends_on:
      - dbstorage
      - clone-detector
    deploy:
      restart_policy:
        condition: none

  dbstorage:
    image: mongo
    restart: always
    command: --quiet --syslog
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - dbstorage:/data/db
      - dbconfig:/data/configdb
    
volumes:
  dbstorage:
  dbconfig:
  qc-volume:
    external: true